

nurse_codes <- c("N0A", "N0B", "N0C", "N0D", "N0E", "N0F", "N0G", "N0H", "N0J", "N0K", "N0L",
                 "N1B", "N1C", "N1H", "N1J", "N1L", "N4D", "N4F", "N4H", "N5D", "N5F", "N5H",
                 "N6A", "N6B", "N6C", "N6D", "N6E", "N6F", "N6G", "N6H", "N6J", "N6K", "N6L",
                 "N7A", "N7B", "N7C", "N7D", "N7E", "N7F", "N7G", "N7H", "N7K", "N7L", "NAA",
                 "NAB", "NAC", "NAD", "NAE", "NAF", "NAG", "NAH", "NAJ", "NAK", "NAL", "NBK",
                 "NCA", "NCB", "NCC", "NCD", "NCE", "NCF", "NCG", "NCH", "NCJ", "NCK", "NCL",
                 "NEH", "P2B", "P2E", "P2C", "P2D", "P3C", "P3D", "P3E", "N7J","P2A","P3A","N1A","NNN")

uk_joiner_nqn <- c("Immediate Joiner",
                "1 Month",
                "1 to 2 Months",
                "2 to 3 Months",
                "3 to 4 Months",
                "4 to 5 Months",
                "5 to 6 Months",
                "6 to 7 Months",
                "7 to 8 Months",
                "8 to 9 Months",
                "9 to 10 Months",
                "10 to 11 Months",
                "11 to 12 Months")

occ_joiner_nqn <- c("Immediate Joiner",
                    "1 Month",
                    "1 to 2 Months")

domestic_trained <- c("England",
                      "Northern Ireland",
                      "Scotland",
                      "Wales",
                      "UK")


south_east_london <- c("07Q",
                       "08A",
                       "TAK",
                       "5A7",
                       "5A8",
                       "RJ1",
                       "RJZ",
                       "5LD",
                       "RJ2",
                       "5LF",
                       "RRU",
                       "07N",
                       "07Q",
                       "08A",
                       "08K",
                       "08L",
                       "72Q",
                       "QKK",
                       "08Q",
                       "RPG",
                       "RV5",
                       "RYQ",
                       "5LE")

north_east_london <- c("5C2",
                       "RF4",
                       "RNJ",
                       "R1H",
                       "5C3",
                       "RWK",
                       "5A4",
                       "RQX",
                       "5C5",
                       "RNH",
                       "07L",
                       "07T",
                       "08F",
                       "08M",
                       "A3A8R",
                       "QMF",
                       "08N",
                       "08V",
                       "08W",
                       "RAT",
                       "5NA",
                       "5C4",
                       "5NC",
                       "RGC")

north_central_london <- c("RVL",
                          "5A9",
                          "RRP",
                          "TAF",
                          "5K7",
                          "RV3",
                          "5C1",
                          "RP4",
                          "5C9",
                          "5K8",
                          "RP6",
                          "07M",
                          "07R",
                          "07X",
                          "08D",
                          "08H",
                          "93C",
                          "QMJ",
                          "RAP",
                          "RAL",
                          "RNK",
                          "RRV",
                          "RKE")

north_west_london <- c("5K5",
                       "RYX",
                       "RQM",
                       "RC3",
                       "5HX",
                       "5H1",
                       "5K6",
                       "RAS2",
                       "5AT",
                       "5HY",
                       "RYJ",
                       "5LA",
                       "R1K",
                       "07P",
                       "09A",
                       "07W",
                       "08C",
                       "08E",
                       "08G",
                       "07Y",
                       "W2U3Z",
                       "QRV",
                       "08Y",
                       "RV8",
                       "RT3",
                       "RPY",
                       "RAN",
                       "RKL",
                       "RFW",
                       "5LC")

south_west_london <- c("RJ6",
                       "5K9",
                       "RVR",
                       "RY9",
                       "RAX",
                       "5A5",
                       "07V",
                       "08J",
                       "08R",
                       "08P",
                       "36L",
                       "QWE",
                       "08T",
                       "08X",
                       "5M6",
                       "RQY",
                       "RJ7",
                       "5M7",
                       "5LG")

devon <- c("RWV",
           "5QQ",
           "RX5",
           "15N",
           "QJK",
           "99P",
           "99Q",
           "RBZ",
           "5F1",
           "RH8",
           "RYF",
           "RA9",
           "R1G",
           "TAL",
           "RK9")


bath_somerset_swindon_and_wiltshire <- c("RVN",
                   "5FL",
                   "RN3",
                   "11E",
                   "92G",
                   "QOX",
                   "12D",
                   "99N",
                   "RBB",
                   "RD1",
                   "RNZ",
                   "5K3",
                   "5QK")

gloucestershire <- c('R1J',
                     'RTQ',
                     'RTE',
                     '5QH',
                     '11M',
                     'QR1')


somerset <- c('11X',
              'QSL',
              'RH5',
              '5QL',
              'RBA',
              'RA4')

cornwall_and_isles_of_scilly <- c('5QP',
                     'RJ8',
                     'QT6',
                     '11N',
                     'REF')

bristol_north_somerset_and_south_gloucestershire <- c('5QJ',
             '11H',
             '15C',
             'QUY',
             '11T',
             '12A',
             'RVJ',
             '5M8',
             '5A3',
             'RA7',
             'RA3')

dorset <- c('5QN',
            'RBD',
            'RDY',
            '5QM',
            '11J',
            'QVV',
            'RD3',
            'RDZ',
            'R0D')


kent_and_medway <- c('RN7',
                 'RVV',
                 '5QA',
                 'RXY',
                 'RYY',
                 'RWF',
                 'RPA',
                 '5L3',
                 '09C',
                 '09E',
                 '09J',
                 '91Q',
                 'QKS',
                 '09W',
                 '10A',
                 '10D',
                 '10E',
                 '99J',
                 '5P9')

frimley <- c('5QG',
             'RWX',
             'RDU',
             'RD7',
             '10G',
             '15D',
             'D4U1Y',
             'QNQ',
             '99M',
             '10T',
             '10C',
             '11C')

sussex <- c('5LQ',
            'RXH',
            '5P7',
            'RXC',
            '5P8',
            '09D',
            '09G',
            '09H',
            '09L',
            '97R',
            '09F',
            '09P',
            '99K',
            '09X',
            'QNX',
            '70F',
            'RPC',
            'RYD',
            'RDR',
            'RX2',
            'RYR',
            '5P6')

hampshire_and_isle_of_wight <- c('RN5',
               '5QC',
               '5QT',
               'R1F',
               '10K',
               'QRL',
               'D9Y0V',
               '10L',
               '10J',
               '10R',
               '10V',
               '10X',
               '11A',
               '5FE',
               'RHU',
               'R1C',
               '5L1',
               'RW1',
               'RHM',
               'RN1')

buckinghamshire_oxfordshire_and_berkshire_west <- c('5QF',
                     'RXQ',
                     '5QD',
                     '10Y',
                     '15A',
                     '14Y',
                     'QU9',
                     '10H',
                     '10M',
                     '10N',
                     '10Q',
                     '10W',
                     '11D',
                     'RBF',
                     'RNU',
                     'RTH',
                     'RHX',
                     '5QE',
                     'RHW',
                     'RYE')

surrey_heartlands <- c('RTK',
            '09N',
            '09Y',
            '99H',
            '92A',
            'QXU',
            'RA2',
            'RXX',
            'RTP',
            '5P5')

hertfordshire_and_worcestershire <- c('R1A',
                   '5CN',
                   '18C',
                   'QGH',
                   '05F',
                   '05J',
                   '05T',
                   '06D',
                   'RWP',
                   'RWQ',
                   '5PL',
                   'RLQ')

birmingham <- c('RXT',
                'RYW',
                '5PG',
                'RQ3',
                'RLU',
                '5MX',
                'RR1',
                '15E',
                'QHL',
                '13P',
                '04X',
                '05P',
                'RRJ',
                'RXK',
                'TAM',
                '5QW',
                '5M1',
                'RRK')

derbyshire <- c('RFS',
                '5N7',
                'RY8',
                '5N6',
                'RXM',
                '15M',
                'QJ2',
                '03X',
                '03Y',
                '04J',
                '04R',
                'RTG')

lincolnshire <- c('RY5',
                  'RP7',
                  '5N9',
                  '71E',
                  '03T',
                  'QJM',
                  '04D',
                  '99D',
                  '04Q',
                  'RWD')

leicestershire_and_rutland <- c('5PC',
                    '5PA',
                    'RT5',
                    '03W',
                    '04C',
                    'QK1',
                    '04V',
                    'RWE')

staffordshire_and_stoke_on_trent <- c('RJF',
                   'RJD',
                   'RRE',
                   '04Y',
                   '05D',
                   '05G',
                   '05Q',
                   '05V',
                   'QNC',
                   '05W',
                   'RLY',
                   '5PH',
                   '5PK',
                   'R1E',
                   '5PJ',
                   'RJE')

shropshire_telford_and_wrekin <- c('05N',
                'M2L0M',
                'QOC',
                '05X',
                'RL1',
                'RXW',
                'R1D',
                '5M2',
                '5MK')

northamptonshire <- c('RNQ',
                      '03V',
                      '04G',
                      '78H',
                      'QPM',
                      'RNS',
                      'RP1',
                      '5PD')

nottinghamshire <- c('5ET',
                     'RX9',
                     '02Q',
                     '04E',
                     '04H',
                     '52R',
                     'QT1',
                     '04K',
                     '04L',
                     '04M',
                     '04N',
                     '5EM',
                     'RX1',
                     '5N8',
                     'RHA',
                     'RK5')

black_country <- c('TAJ',
                   'RYK-X',
                   'RNA',
                   'RYK',
                   '5PE',
                   'D2P2L',
                   'QUA',
                   '05C',
                   '05L',
                   '05Y',
                   '06A',
                   'RL4',
                   '5PF',
                   'RBK',
                   '5M3',
                   'RYA',
                   '5MV')

coventry_and_warwickshire <- c('RYG',
                           '5MD',
                           'RLT',
                           '05A',
                           'B2M3M',
                           'QWU',
                           '05R',
                           '05H',
                           'RJC',
                           'RKB',
                           '5PM')

mid_and_south_essex <- c('RDD',
                     'R1L',
                     'RAJ',
                     'RQ8',
                     '5PX',
                     '99E',
                     '99F',
                     'QH8',
                     '06Q',
                     '99G',
                     '07G',
                     '5P1',
                     'RWN',
                     '5PY')

bedfordshire_luton_and_milton_keynes <- c('RC1',
                  'RV7',
                  'RC9',
                  '5P2',
                  '5GC',
                  '5CQ',
                  'RD8',
                  '06F',
                  'M1J4Y',
                  'QHG',
                  '06P',
                  '04F')

suffolk_and_north_east_essex <-c('RDE',
                       'RGQ',
                       '06T',
                       'QJG',
                       '07K',
                       '5PW',
                       'RRD',
                       'RT6',
                       '5PT',
                       'RGR')

hertfordshire_and_west_essex <- c('RWH',
                   '5P3',
                   'RY4',
                   'RWR',
                   '5QV',
                   '06K',
                   'QM7',
                   '06N',
                   '07H',
                   'RQW',
                   '5PV',
                   '5P4',
                   'RWG')

norfolk_and_waveney <- c('5PR',
             'RGP',
             '06M',
             '26A',
             'QMM',
             '06V',
             '06W',
             '06Y',
             '07J',
             'RM1',
             'RMY',
             'RY3',
             '5PQ',
             'RCX')

cambridgeshire_and_peterborough <- c('RGT',
                    'RT1',
                    'RYV',
                    '5PP',
                    'RYC',
                    'RQQ',
                    '06H',
                    'QUE',
                    'RGN',
                    '5PN',
                    'RGM')

lancashire_and_south_cumbria <- c('5CC',
                'TAP',
                '5HP',
                'RXL',
                'RJX',
                '5NG',
                'RXR',
                '5NH',
                'RW5',
                'RXN',
                '00Q',
                '00R',
                '00X',
                '01A',
                '02M',
                '01E',
                'QE1',
                '01K',
                '02G',
                '5NF',
                'RTX')


greater_manchester <- c('5HG',
                        'RMC',
                        '5HQ',
                        '5JX',
                        'RW3',
                        'RBV',
                        'RXV',
                        '5NQ',
                        'TAE',
                        '5NT',
                        'R0A',
                        '00T',
                        '00V',
                        '00W',
                        'QOP',
                        '01D',
                        '14L',
                        '01M',
                        '00Y',
                        '01G',
                        '01N',
                        '01W',
                        '01Y',
                        '02A',
                        '02H',
                        'RX7',
                        'RM3',
                        '5J5',
                        'RW6',
                        'RT2',
                        '5F5',
                        'RWJ',
                        '5F7',
                        'RMP',
                        '5LH',
                        'RM4',
                        '5NR',
                        'RM2',
                        'RRF')

cheshire_and_merseyside <-c('RBS',
             'RY2',
             '5NP',
             'RXA',
             'REN',
             'RJR',
             'RJN',
             '5NM',
             '5J4',
             'RY1',
             'RBQ',
             '5NL',
             'REM',
             'REP',
             'RBN',
             'RW4',
             'RBT',
             'QYG',
             '27D',
             '01C',
             '01F',
             '01J',
             '99A',
             '01R',
             '01T',
             '01X',
             '02D',
             '02E',
             '02F',
             '12F',
             'RTV',
             'RQ6',
             '5NJ',
             'RVY',
             'RET',
             'RWW',
             '5J2',
             '5NN',
             'RY7',
             '5NK',
             'RBL')


south_yorkshire <-c('RFF',
                         '5JE',
                         'RP5',
                         '5N5',
                         '02P',
                         '02X',
                         '03L',
                         '03N',
                         'QF7',
                         'RXE',
                         'RFR',
                         '5H8',
                         'RCU',
                         'TAH',
                         '5N4',
                         'RHQ')

north_east_and_north_cumbria <- c('RLN',
                                  'RXP',
                                  '5ND',
                                  '5NE',
                                  'RX4',
                                  '5J9',
                                  'RR7',
                                  '5KF',
                                  '5D9',
                                  '5KM',
                                  '5D7',
                                  'RTD',
                                  '84H',
                                  '00C',
                                  '00D',
                                  '00F',
                                  '03D',
                                  '00G',
                                  '01H',
                                  '00J',
                                  'QHM',
                                  '99C',
                                  '00M',
                                  '00P',
                                  '16C',
                                  'RNN',
                                  'RNL',
                                  'RX6',
                                  'RVW',
                                  '5D8',
                                  'TAC',
                                  'RTF',
                                  '5QR',
                                  'RTR',
                                  'R0B',
                                  'RE9',
                                  '5KG',
                                  '5E1',
                                  '5KL',
                                  'RX3')

humber_and_north_yorkshire <- c('RLN',
                                'RXP',
                                '5ND',
                                '5NE',
                                'RX4',
                                '5J9',
                                'RR7',
                                '5KF',
                                '5D9',
                                '5KM',
                                '5D7',
                                'RTD',
                                '84H',
                                '00C',
                                '00D',
                                '00F',
                                '03D',
                                '00G',
                                '01H',
                                '00J',
                                'QHM',
                                '99C',
                                '00M',
                                '00P',
                                '16C',
                                'RNN',
                                'RNL',
                                'RX6',
                                'RVW',
                                '5D8',
                                'TAC',
                                'RTF',
                                '5QR',
                                'RTR',
                                'R0B',
                                'RE9',
                                '5KG',
                                '5E1',
                                '5KL',
                                'RX3')


west_yorkshire <- c('RCF',
                    '5NY',
                    'TAD',
                    'RAE',
                    'RWY',
                    '5J6',
                    '5N2',
                    'RGD',
                    'RY6',
                    '5N1',
                    'RR8',
                    'RXF',
                    '02N',
                    '02W',
                    '36J',
                    '02R',
                    '02T',
                    '03A',
                    '03E',
                    'X2C4Y',
                    '15F',
                    '02V',
                    '03G',
                    '03C',
                    '03J',
                    '03R',
                    'QWO',
                    'RXG',
                    '5N3',
                    'RX8')